--- #YAML:1.0
name:               Gtk2-Ex-Entry-Pango
version:            0.10
abstract:           Gtk2 Entry that accepts Pango markup.
author:
    - Emmanuel Rodriguez <potyl@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Gtk2:         1.100
    Gtk2::Pango:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
