--- #YAML:1.0
name:                Gtk2-Ex-Entry-Pango
version:             0.05
abstract:            Gtk2 Entry that accepts Pango markup.
license:             ~
author:              
    - Emmanuel Rodriguez <potyl@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Gtk2:                          0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
